// One-off capture script. Runs a real chat completion through the OpenAI
// SDK under an InMemorySpanExporter that follows the OpenTelemetry GenAI
// semantic conventions, and writes the resulting span dump to
// `test/fixtures/openai.spans.json` for the mapper test to load.
//
// Uses the `wrapOpenAI` helper from `@agnost/sdk/openai` — so the fixture
// is generated by the same code path the SDK ships, not by a parallel
// hand-rolled emitter.
//
// Works against any OpenAI-compatible endpoint by setting OPENAI_BASE_URL.
// We capture against Groq's OpenAI-compatible API in development to avoid
// burning OpenAI quota; `AGNOST_CAPTURE_PROVIDER` controls the
// `gen_ai.system` value so the fixture stays honest about which provider
// actually served the request.
//
//   OPENAI_API_KEY               — required
//   OPENAI_BASE_URL              — optional; defaults to OpenAI's endpoint
//   AGNOST_CAPTURE_MODEL         — optional; defaults to gpt-4o-mini
//   AGNOST_CAPTURE_PROVIDER      — optional; default "openai"

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { trace, SpanKind, SpanStatusCode } from "@opentelemetry/api";
import {
  BasicTracerProvider,
  InMemorySpanExporter,
  SimpleSpanProcessor,
  type ReadableSpan,
} from "@opentelemetry/sdk-trace-base";
import OpenAI from "openai";
import { wrapOpenAI } from "../../src/profiles/openai.js";

const FIXTURE_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "openai.spans.json",
);

const MODEL = process.env["AGNOST_CAPTURE_MODEL"] ?? "gpt-4o-mini";
const PROVIDER = process.env["AGNOST_CAPTURE_PROVIDER"] ?? "openai";

if (!process.env["OPENAI_API_KEY"]) {
  console.error("[capture-openai] OPENAI_API_KEY not set.");
  process.exit(1);
}

const memoryExporter = new InMemorySpanExporter();
const provider = new BasicTracerProvider({
  spanProcessors: [new SimpleSpanProcessor(memoryExporter)],
});
provider.register();
const tracer = trace.getTracer("agnost-capture-openai", "0.0.1");

const rawClient = new OpenAI({
  apiKey: process.env["OPENAI_API_KEY"],
  baseURL: process.env["OPENAI_BASE_URL"],
});
const client = wrapOpenAI(rawClient);

const tools = [
  {
    type: "function" as const,
    function: {
      name: "get_weather",
      description: "Get current weather for a city.",
      parameters: {
        type: "object",
        properties: { city: { type: "string", description: "City name" } },
        required: ["city"],
      },
    },
  },
];

const messages = [
  {
    role: "system" as const,
    content: "You are a helpful weather assistant. Use the tool when asked.",
  },
  {
    role: "user" as const,
    content: "What's the weather in Paris today? My email is jane.doe@example.com.",
  },
];

async function run(): Promise<void> {
  // The wrapped client emits the chat span automatically. We rewrite
  // gen_ai.system on the captured span after-the-fact so the fixture
  // honestly reflects whichever provider we hit (Groq in dev, OpenAI
  // in real captures). Production users don't need this — the profile
  // hard-codes "openai" because that's the SDK they're calling.
  const completion = (await client.chat.completions.create({
    model: MODEL,
    messages,
    tools,
    tool_choice: "auto",
    temperature: 0,
  })) as {
    choices?: {
      message?: {
        content?: string | null;
        tool_calls?: {
          id?: string;
          type?: string;
          function?: { name?: string; arguments?: string };
        }[];
      };
    }[];
  };

  // Emit a separate execute_tool span (agent seam). We synthesize this
  // because the OpenAI SDK itself doesn't run tools — agent frameworks do.
  const firstTool = completion.choices?.[0]?.message?.tool_calls?.[0];
  if (firstTool?.type === "function" && firstTool.function?.name) {
    const toolResult = JSON.stringify({ city: "Paris", temp_c: 17, sky: "cloudy" });
    const toolSpan = tracer.startSpan(`execute_tool ${firstTool.function.name}`, {
      kind: SpanKind.INTERNAL,
      attributes: {
        "gen_ai.operation.name": "execute_tool",
        "gen_ai.tool.name": firstTool.function.name,
        "gen_ai.tool.call.id": "call_demo_1",
      },
    });
    toolSpan.addEvent("gen_ai.tool.message", {
      role: "tool",
      content: firstTool.function.arguments ?? "",
    });
    toolSpan.setAttribute("gen_ai.tool.result", toolResult);
    toolSpan.setStatus({ code: SpanStatusCode.OK });
    toolSpan.end();

    const assistantMessage = completion.choices?.[0]?.message;
    await client.chat.completions.create({
      model: MODEL,
      messages: [
        ...messages,
        {
          role: "assistant",
          content: assistantMessage?.content ?? null,
          tool_calls: [
            {
              id: firstTool.id ?? "call_demo_1",
              type: "function",
              function: {
                name: firstTool.function.name,
                arguments: firstTool.function.arguments ?? "{}",
              },
            },
          ],
        },
        {
          role: "tool",
          tool_call_id: firstTool.id ?? "call_demo_1",
          content: toolResult,
        },
      ],
      temperature: 0,
    });
  }

  // Rewrite the captured chat span's gen_ai.system to honest provider.
  // (See note above — only the capture script does this.)
  await provider.forceFlush();
  const spans: ReadableSpan[] = memoryExporter.getFinishedSpans();
  for (const s of spans) {
    if (s.name.startsWith("chat ") && PROVIDER !== "openai") {
      (s.attributes as Record<string, unknown>)["gen_ai.system"] = PROVIDER;
      for (const e of s.events) {
        if (e.attributes && "content" in e.attributes) {
          (e.attributes as Record<string, unknown>)["gen_ai.system"] = PROVIDER;
        }
      }
    }
  }

  const serialized = spans.map((s) => ({
    name: s.name,
    kind: s.kind,
    attributes: s.attributes,
    events: s.events.map((e) => ({
      name: e.name,
      attributes: e.attributes,
      time: e.time,
    })),
    startTime: s.startTime,
    endTime: s.endTime,
    status: s.status,
    traceId: s.spanContext().traceId,
    spanId: s.spanContext().spanId,
  }));

  mkdirSync(dirname(FIXTURE_PATH), { recursive: true });
  writeFileSync(FIXTURE_PATH, JSON.stringify(serialized, null, 2), "utf8");
  console.log(`[capture-openai] wrote ${spans.length} span(s) to ${FIXTURE_PATH}`);

  await provider.shutdown();
}

run().catch((err) => {
  console.error("[capture-openai] failed:", err);
  process.exit(1);
});
